const mockData = [
  { name: '十八', value: '中原西部地区有一个地方号称天府之国' },
  { name: '十八', value: '它地处长江上游' },
  { name: '十八', value: '那里鸟语花香 四季分明' },
  { name: '十八', value: '地理资源得天独厚' },
  { name: '十八', value: '自然风景与人文景观交相辉映' },
  { name: '十八', value: '四周群山环绕' },
  { name: '十八', value: '于是中原人士称其为 山~~~~城' },
  { name: '墨墨冰', value: '今天晚上要停电' },
  { name: '墨墨冰', value: '漆黑我两的视线' },
  { name: '墨墨冰', value: '你到了这里看不见' },
  { name: '墨墨冰', value: '朝天门在较场口旁边' },
  { name: '墨墨冰', value: '霓虹灯正眨着眼' },
  { name: '墨墨冰', value: '月亮靠近大都会顶点' },
  { name: '墨墨冰', value: '冰粉凉虾嘿么甜' },
  { name: '墨墨冰', value: '红糖水再给我放一点' },
  { name: '墨墨猪', value: '吃火锅不数芊芊' },
  { name: '墨墨猪', value: '吃串串才数芊芊的我' },
  { name: '墨墨猪', value: '家住在五里店' },
  { name: '墨墨猪', value: '爱看重庆台' },
  { name: '墨墨猪', value: '麻辣笑星在表演' },
  { name: '墨墨冰', value: '西政的帅哥表情看来很腼腆' },
  { name: '墨墨冰', value: '川外的美女热情大方笑开言' },
  { name: '墨墨冰', value: '朝天门沿线' },
  { name: '墨墨冰', value: '到码头边' },
  { name: '墨墨冰', value: '能看见两条江水交界线' },
  { name: '墨墨猪', value: '从小被两条江水泡大的我们' },
  { name: '墨墨猪', value: '如今在轻轨上面仰望着蓝天' },
  { name: '墨墨猪', value: '磁器口人潮涌' },
  { name: '墨墨猪', value: '百姓跟风' },
  { name: '墨墨猪', value: '买一袋麻花还要排长龙' },
  { name: '墨墨猪', value: '一点不轻松' },
  { name: '墨墨冰', value: '吃火锅不数芊芊' },
  { name: '墨墨冰', value: '吃串串才数芊芊的我' },
  { name: '墨墨冰', value: '眼睛还会放电' },
  { name: '墨墨冰', value: '跑到解放碑' },
  { name: '墨墨冰', value: '人民公园打太极拳' },
  { name: '墨墨猪', value: '当老板二十四小时忙着找钱' },
  { name: '墨墨猪', value: '打工仔兢兢业业工作不悠闲' },
  { name: '墨墨猪', value: '望江耍一天' },
  { name: '墨墨猪', value: '去泡温泉' },
  { name: '墨墨猪', value: '老汉说又费马达又费电' },
  { name: '墨墨冰', value: '从小喝嘉陵江水长大的我们' },
  { name: '墨墨冰', value: '不喜欢汉堡西餐只爱吃小面' },
  { name: '墨墨冰', value: '棒棒军嘿么凶' },
  { name: '墨墨冰', value: '东西很重' },
  { name: '墨墨冰', value: '他一样扛上扛下到处贡' },
  { name: '墨墨冰', value: '非常的轻松' },
  { name: '墨墨猪', value: '朝天门沿线' },
  { name: '墨墨猪', value: '到码头边' },
  { name: '墨墨猪', value: '能看见两条江水交界线' },
  { name: '墨墨冰', value: '等到三峡大坝水装满那天' },
  { name: '墨墨冰', value: '我们的城市绝对不会再停电' },
  { name: '合', value: '岁月一年一年' },
  { name: '合', value: '时光改变' },
  { name: '合', value: '誉存也有会腾飞的一天' },
  { name: '合', value: '我们能看见' },
  { name: '十八', value: '朝辞白帝彩云间 千里江陵一日还' },
  { name: '十八', value: '两岸猿声啼不住 轻舟已过万重山' },
  { name: '十八', value: '鼓声三下红旗开 两龙跃山呼水来' },
  { name: '腊肠', value: '棹影斡波飞万剑 鼓声劈浪鸣千雷' },
  { name: '腊肠', value: '鬼关外逢人日 踏碛千家万家出' },
  { name: '腊肠', value: '竹枝惨戚云不动 剑器联翩日将夕' }
]
export default mockData;
